spring:
  rabbitmq:
    addresses: localhost:5672, localhost:5673, localhost:5674    
    listener:      
      simple:
        retry:        
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
logging:  level:    org.springframework.amqp.rabbit: INFO
queue:
  U2571: flight.eu.U2571
  U2771: flight.eu.U2771
  FR691: flight.uk.FR691
  UA221: flight.us.UA221
flight:
  code: flight.eu.U2571